/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IFaSolidDiceFive: typeof import('~icons/fa-solid/dice-five')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('~icons/heroicons-outline/menu-alt2')['default']
    'IMdi:diceD12': typeof import('~icons/mdi/dice-d12')['default']
    IMdiLightAlarm: typeof import('~icons/mdi-light/alarm')['default']
    IRiApps2Line: typeof import('~icons/ri/apps2-line')['default']
    'ISolar:addCircleLinear': typeof import('~icons/solar/add-circle-linear')['default']
    KitAsyncComponent: typeof import('./kits/KitAsyncComponent.vue')['default']
    KitError: typeof import('./kits/KitError.vue')['default']
    KitImage: typeof import('./kits/KitImage.vue')['default']
    KitListKV: typeof import('./kits/KitListKV.vue')['default']
    KitLoader: typeof import('./kits/KitLoader.vue')['default']
    KitLoading: typeof import('./kits/KitLoading.vue')['default']
    KitLogin01: typeof import('./kits/KitLogin01.vue')['default']
    KitTable: typeof import('./kits/KitTable.vue')['default']
    LayApp: typeof import('./layouts/LayApp.vue')['default']
    LayDashboard: typeof import('./layouts/LayDashboard.vue')['default']
    LayDefault: typeof import('./layouts/LayDefault.vue')['default']
    LayEcommerce: typeof import('./layouts/LayEcommerce.vue')['default']
    LayHome: typeof import('./layouts/LayHome.vue')['default']
    LayNone: typeof import('./layouts/LayNone.vue')['default']
    MyCustom: typeof import('./CustomResolved.vue')['default']
    PiniaTest: typeof import('./components/PiniaTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoForm: typeof import('./components/TodoForm.vue')['default']
    TodoList: typeof import('./components/TodoList.vue')['default']
  }
}
